# Generated by Django 4.0.5 on 2022-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('travel', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('features', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('car', models.CharField(max_length=111)),
                ('price', models.IntegerField()),
                ('first_name', models.CharField(max_length=111)),
                ('last_name', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('phone', models.IntegerField()),
                ('pickup_location', models.CharField(max_length=111)),
                ('drop_location', models.CharField(max_length=111)),
                ('pickup_date', models.CharField(max_length=111)),
                ('pickup_time', models.CharField(max_length=111)),
                ('special', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media')),
                ('Profession', models.CharField(max_length=50)),
            ],
        ),
    ]
